# Reference: https://www.linkedin.com/pulse/building-flask-application-mysql-database-using-docker-agarwal/

version: '3.7'

services:
    server:
        build: ./server
        restart: always
        links:
            - database
        ports:
            - "5000:5000"
        depends_on:
            - database
            
    database:
        image: mysql:latest
        restart: always
        ports:
            - "3906:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pwd
        volumes:
            - ./database/init:/docker-entrypoint-initdb.d
            - ./database/data:/var/lib/mysql
        healthcheck:
            test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-ppwd']
            timeout: 20s
            retries: 10
